// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KQTFt6pWCPPmo8ai_wBd6Jg9ney5r9M',
    appId: '1:512154661335:web:71401bccb0dcc008ad1b92',
    messagingSenderId: '512154661335',
    projectId: 'soundrop-7fac2',
    authDomain: 'soundrop-7fac2.firebaseapp.com',
    storageBucket: 'soundrop-7fac2.firebasestorage.app',
    measurementId: 'G-52E7EBFJB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaxqNWYAEoCcCZroo8osvz7a2498KXtBo',
    appId: '1:512154661335:android:18d30911e295757ead1b92',
    messagingSenderId: '512154661335',
    projectId: 'soundrop-7fac2',
    storageBucket: 'soundrop-7fac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsInNxVUlt4aJoF1yWKasUURvzQL3dJrM',
    appId: '1:512154661335:ios:cc9d3b6a473a6f42ad1b92',
    messagingSenderId: '512154661335',
    projectId: 'soundrop-7fac2',
    storageBucket: 'soundrop-7fac2.firebasestorage.app',
    iosBundleId: 'com.nicchizu.soundDrop',
  );
}
